radixdlt/olympia-wallet

src/components/FormField.vue
src/validations.ts
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue

`type='number'` input elements are [problematic][1].  On the web, they
offer a myriad of bugs and strange behaviors.  This PR refactors the
amount input fields to use validators to validate an amount rather than
relying on an input field to sanitize the values as they arrive.
[1]: https://css-tricks.com/what-to-use-instead-of-number-inputs/

fix: Replace number inputs with validated text fields

---

src/views/Wallet/WalletConfirmTransactionModal.vue

The transaction confirmation modal was throwing an error because stake transactions do not include a message.

fix: Staking Confrmation Modal does include a message

---

src/components/TransactionListItem.vue

Only display actions relevant to the active address
Linear: https://linear.app/township/issue/RDX-124/make-display-of-complex-txes-just-slightly-more-clever

fix: Transactions should only display actions relevant to the active address

---

.github/workflows/release-please.yml

I was able to sign a build locally with these certificates that are now stored in the repo secrets.  This should just work assuming I wrote the yaml correctly.

fix: Mac OS Builds should be signed

---

package.json
src/components/FormField.vue
src/views/Wallet/WalletTransaction.vue
src/views/Wallet/index.vue
yarn.lock

We had previously attempted to eagerly pre-build transactions before the user chose to submit a transaction so that the fee could be calculated.  Even at a two second throttle, this caused both wallet ux issues and major performance problems on the network.  This PR reverts those eager pre-build changes and also adds a loader when switching accounts.

Revert fee calculation and add a loader

---

src/assets/tailwind.css
src/components/BigAmount.vue
src/main.ts

https://www.loom.com/share/a5be6bb6e1364c2da76063f4b96de68b
Improvements:
* Don't purge custom vendor styles by avoiding the `@layer` tailwind directive
* Currency amounts should also use a toast
* Toasts should stay on the screen for less time.

fix: Toast Updates

---

src/text/index.ts
src/views/Wallet/WalletStaking.vue

https://linear.app/township/issue/RDX-114/add-links-to-stakingunstaking-explanatory-copy

chore(copy): Update the copy for the staking and unstaking forms

---

src/views/Wallet/WalletHistory.vue
src/views/Wallet/index.vue

The `TransactionStateUpdate` type was being cast first to an unknown then to a `TransactionIntent`, which I assume was done to get past a type error.  This PR stores the draftTransaction as the correct `TransactionIntent`

fix: Correctly type a pending transaction so it displays in history correctly

---

src/views/Wallet/index.vue

Depending on `radix.activeAddress()` to update unstakes does not work as expected, since the active address stream will only push new values when changing account (or when starting the app). 
Using the helper method `radix.unstakingPositions()` however, periodically pushes values and therefore will keep triggering the `subscribe` logic, updating the state as expected.

use high level method for unstakes

---

src/components/AccountListItem.vue
src/components/ActionListItemStakeTokens.vue
src/components/ActionListItemTransferTokens.vue
src/components/ActionListItemUnstakeTokens.vue
src/components/ClickToCopy.vue
src/components/StakeListItem.vue
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletLedgerVerifyAddressModal.vue
src/views/Wallet/WalletOverview.vue
src/views/Wallet/WalletSidebarAccounts.vue
src/views/Wallet/WalletSidebarDefault.vue
src/views/Wallet/WalletTransaction.vue
src/views/Wallet/index.vue
yarn.lock

This PR adds the verify address modal functionality to all relevant copy icons. When a hardware wallet is the active account, it will show the verify modal and cue the Ledger to verify the address before copying.

feat: add proper verify address modals everywhere

---

src/components/StakeListItem.vue
src/views/Wallet/WalletStaking.vue

> Nasty bug here. Apparently unstaking sometimes causes the Stake & Unstake screen to become inaccessible, like this. Details in thread.
If you want to test, I think it should be replicatable by:
Stake to tv1qguchws4ewpt98uwwkrpyat6jz5kdd7cvddsd7me22c2ncscyny7j5qvv05
Wait 30 minutes to make sure an epoch has elapsed, allowing you to unstake
Unstake all of your tokens again from that validator.
Try to load the Stake & Unstake screen again.
Exception was being thrown due to reducing over empty lists.

fix: Stake reducers need an initial value for empty lists

---

src/components/ActionListItemStakeTokens.vue
src/components/ActionListItemTransferTokens.vue
src/components/ActionListItemUnstakeTokens.vue
src/components/TransactionListItem.vue
src/text/index.ts
src/views/Home/HomeEnterPasscode.vue
src/views/Settings/SettingsRevealMnemonic.vue
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletSidebarAccounts.vue
src/views/Wallet/WalletStaking.vue

- chore: Add Choose Accounts copy to sidebar menu
- chore: Cancel button was too low
- fix: Show token label as text in confirmation modal
- chore: Validators arrow was too far away
- chore: Consistent font size in transaction list items
- chore: Click to decrypt should look clickable
- chore: Remove password required copy from login
This addresses most of the issues in the linear story. The last remaining one
includes work for updating the PIN UI which is outlined in https://linear.app/township/issue/RDX-152/change-pin-entry-bubble-presentation
It also closes https://linear.app/township/issue/RDX-170/remove-password-error-message

chore: Various design enhancements

---

src/views/Wallet/WalletTransaction.vue

When an address has no native (XRD) tokens but does have alt tokens, a user should still be able to send a transaction.  
Previously the 'currency' value would never be set, resulting in a loader that never disappeared.

fix: Addresses without XRD should be able to send transactions

---

src/components/StakeListItem.vue
src/store/_types.ts
src/views/Wallet/WalletStaking.vue

The list of current positions displayed on the stake page was depending
on the index of the stake in the sorted list as a key.  Over time, the
index of a position can change on the sorted list as a user interacts
with the positions and as the values of the positions change from
polling.
This commit fixes these inconsistencies by depending on the address of
the valdiator as a key, extending the `Position` type by adding the
address as a string.
This PR also fixes an out of date `CopyToClipboard` call that was
sending a `text` prop rather then the updated `address` prop.

fix: Stake List was using an unpredicatable key

---

src/actions/electron/hardware-wallet.ts
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletLedgerVerifyAddressModal.vue
src/views/Wallet/WalletTransaction.vue
src/views/Wallet/index.vue

- Throw error when device is disconnected while trying to communicate with a ledger device.
- Subscribe to ledger device events: device disconnected, device connected, app open, app closed.
I have only added logging as a reaction to these events. Please handle the events in any way you deem suitable, for example setting some shared state to be used in components. 
NOTE: Due to some inconsistent behavior with the usb events, I had to hardcode a timer in order to prevent multiple device connection events from firing when opening/closing the ledger app. This might be a bit unreliable between different machines ... but this timer can be increased to increase the reliability. The downside of increasing the timer is that we then introduce a longer delay for the device connection events to fire. …

fix ledger connection stuff

---

vue.config.js

The auto-updater needs the zip files for downloading new releases.

fix: Include zip file in mac electron-builder targets

---

src/views/Wallet/index.vue

This PR fixes a regression in the error handling caused by the addition of ledger errors.
The error handling subscriptions have been updated for the following fixes:
- Errors that originate from the API do not have the expected shape as described by typescript
- Referenced staking components do not have values if they're not currently rendered.

fix: Transaction Error Handling Regression

---

.envrc.sample
.github/workflows/release-latest.yml
.github/workflows/release-ledger.yml
.github/workflows/release-main.yml
src/components/StakeListItem.vue
src/helpers/network.ts
src/views/CreateWallet/index.vue
src/views/Home/index.vue
src/views/Settings/SettingsResetPassword.vue
src/views/Settings/index.vue
src/views/Wallet/index.vue

This PR improves how we manage network selection in environment variables, and should help improve our Github build process long term.
We now expect an `VUE_APP_NETWORK_NAME` environment variable. Currently, we only support values of `stokenet` or `mainnet`. If we don't receive one of those two values, we throw an error. Choosing a network implictly has burned us in the past, I'd prefer we just bomb out.

chore: improve how we handle network selection

---

src/helpers/network.ts
src/helpers/validateRadixTypes.ts

This PR introduces a lightweight check to verify that user input addresses can both be safely unwrapped and also have valid preambles (`rdx` for mainnet, `tdx` for stokenet, etc) for the wallet's current network.

fix: validate network addresses for active network

---

src/views/Wallet/WalletConfirmTransactionModal.vue

This PR contains one fix and one new feature:
- The confirmation modal form previously contained two `button` elements. This was preventing the form from submitting successfully and closing the modal. Changing the cancel `button` to an anchor tag corrected the issue.
- Adds functionality to close the confirmation modal when the escape key is pressed.

Feat: The confirmation modal should submit on Enter, and Cancel on Escape.

---

src/views/Wallet/WalletTransaction.vue

This PR prevents an error from occurring when a user attempts to view the Send Token screen when they have no token balances.

fix: prevent error on send screen when no balances

---

src/views/Wallet/WalletSidebarAccounts.vue
src/views/Wallet/index.vue

With the (temporary) release of v1.1.0 a bug was introduced due to the wallet's lagging implementation of new SDK functionality. To allow for multiple derived hardware wallets, the SDK allow hardware wallet accounts to be stacked on the general accounts list. Without proper wallet changes this resulted in two undesirable behaviors:
- As hardware wallet accounts were derived in a single Radix SDK object session, each account was pushed on the general stack of accounts. Meaning, those accounts now began to display in our primary account list, which should only show Local HD Wallet accounts. The fix in this PR is to filter accounts shown there, displaying only those where `account.signingKey.isLocalHDSigningKey` is true.
- Secondly, this also meant that using the `next` option to derive new …

Fix: Hardware Wallet account derivation

---

src/text/index.ts
src/views/Wallet/WalletErrorModal.vue
src/views/Wallet/index.vue

This PR adds functionality to present users with an error modal when they attempt to derive a new Radix address with one already loaded. In the current build, this is only possible by using multiple ledger devices. Users are required instead to explicitly remove a hardware wallet before adding another.
It also adds a reusable error component for future use. :)

chore: Show error when new hw address added

---

src/components/MnemonicDisplay.vue
src/views/Settings/SettingsRevealMnemonic.vue

fix: Show Word Numbers when revealing the seed phrase in settings

---

src/helpers/explorerLinks.ts
src/helpers/formatter.ts
src/views/Wallet/WalletOverview.vue

This PR matches the design style and rearranges other token balance divs. Link in corner leads to token RRI page in Explorer.
[Part of RDX-69](https://linear.app/township/issue/RDX-69/feat-token-rris)
[UPDATED Demo w/ RRI String truncation](https://www.loom.com/share/96704d766dfa44378e273b63676a9311)
[Previous Demo no RRI String truncation](https://www.loom.com/share/65c2cc327d7b4fbdbb76e01c6d806ed9)

feat: show non xrd tokens in wallet

---

src/views/Wallet/WalletOverview.vue

This PR changes the styling so the other token balance arrow svg matches token name spacing

chore: update styling of Wallet Overview page

---

.github/workflows/release-latest.yml

There's a need to deliver stokenet builds for testing purposes. We'd like those stokenet builds to be produced as similarly as possible to our mainnet builds. So, temporarily, all builds on the latest channel will target stokenet.
This work will be undone when the imminent Network Selection work is complete.

chore: temporarily, latest builds target stokenet

---

src/components/ActionListItemUnstakeTokens.vue
src/components/TransactionListItem.vue
src/composables/index.ts
src/composables/useNativeToken.ts
src/composables/useStaking.ts
src/composables/useTokenBalances.ts
src/composables/useTransactions.ts
src/composables/useWallet.ts
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletOverview.vue
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue
src/views/Wallet/index.vue

Now that we've done all the hard work of moving _all_ of the logic from the `Wallet/index.vue` component into a few composables (is that the right word?), let's take it one step forward.
This PR separates out two major concerns of the `useWallet` composition api into separate, independent composables.
Doing this allows for each _route_ in the view tree to handle it's own subscriptions.  Each route that needs the token balances or native token associated with the authenticated wallet, can subscribe to that data independently, and then _unsubscribe_ when it's done.  This simplifies the API, increases separation of concerns, and also completely solves the problem of the `WalletOverview` and other views breaking on network change.
We should do this for:
If we continue down this path, this …

feat: Introduce NativeToken and TokenBalances composables

---

src/actions/electron/data-store.ts
src/actions/vue/data-store.ts
src/components/ClickToCopy.vue
src/composables/useRadix.ts
src/composables/useTransactions.ts
src/composables/useWallet.ts
src/electron-store/migrations.ts
src/views/RestoreWallet/index.vue
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletSidebarAccounts.vue
src/views/Wallet/WalletSidebarDefault.vue
src/views/Wallet/WalletTransaction.vue

Looks like the migration misspelled `hardware`, users who have updated to the unreleased alpha will need to replace `handware` with `hardware` in `wallet.json`

Fix: Network specific account indexes and hardware addresses

---

src/views/Wallet/WalletTransaction.vue

https://linear.app/township/issue/RDX-240/bug-currency-picker-not-populated-on-send-tokens-screen

fix: Transaction Currency Selector wasn't working

---

src/views/Wallet/WalletConfirmTransactionModal.vue

This fixes a bug where the WalletConfirmTransactionModal would crash for both staking and unstaking

fix: Staking transactions should reference nativeToken not selectedCurrency

---

src/views/Wallet/WalletLedgerInteractionModal.vue
src/views/Wallet/WalletSidebarDefault.vue
src/views/Wallet/WalletTransaction.vue

There were several remaining ledger integrations points that utilized the vue-2
style `$emit` events that had been removed in the refactor.

fix: Refactor old  from the wallet views linked to ledger integrations

---

src/views/Wallet/index.vue

This PR updates the styling of the non-mainnet warning to be more visible/obvious on screens with content that may have to scroll into view.

chore: update styling of the non-mainnet warning

---

src/text/index.ts
src/views/Settings/SettingsResetPin.vue

This PR updates the title of the confirmation button to `Confirm` on the Change PIN screen.

fix: correct pin change button title

---

src/views/Wallet/WalletConfirmTransactionModal.vue

This PR fixes the cancel button on the transaction confirmation modal, correctly dismissing the modal.

fix: the cancel button should close tx conf modal

---

src/components/OtherTokenBalanceListItem.vue

This PR updates non-XRD balances to have smaller type sizes, so they don't dominate the balances page.
Before
After

chore: update styling of non-xrd balances

---

src/composables/useTransactions.ts
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue

This PR sets up the the transaction and stake/unstake views to correctly watch the `transactionErrorMessage` value from the `useTransaction` composable to watch for any potential errors, and displays them appropriately.
It also resets the value of `transactionErrorMessage` to null in `useTransaction` when any new transaction is created, so that repeated failures are reported to views watching `transactionErrorMessage`.

fix: correctly present build errors on Transaction and Stake/Unstake screens

---

src/electron-store/migrations.ts

Fixes a bug where users with an existing wallet.json had their values overridden by the migration

fix: Don’t override existing values in wallet.json in initial migration

---

src/components/AccountListItem.vue
src/views/Wallet/WalletConfirmTransactionModal.vue

* removes an error from the transaction confirmation modal if the native token has not been initialized yet
* account list items had a non-reactive address

Two small fixes

---

src/components/AccountListItem.vue
src/views/Wallet/WalletSidebarAccounts.vue

This PR correctly highlights the active account, whether it be a software account or a hardware account.
https://www.loom.com/share/d7777b984cc74c55806d83da8b9e07b1

fix: correctly highlight active account

---

src/text/index.ts
src/views/Settings/SettingsSelectNode.vue
src/views/Wallet/WalletOverview.vue

This PR:
- updates the copy for custom node selection errors
- hides non-XRD tokens when switching accounts
- fixes a typo in the non-mainnet warning copy.

chore: final 1.2.0 release tweaks

---

src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletTransaction.vue

In the Great Refactor we introduced a regression where on the Amount in the transaction confirmation modal we always displayed the `nativeToken` symbol, where we should be showing the transaction's `selectedCurrency` symbol. This PR fixes that issue. It also ensures that we show the `nativeToken` symbol when staking/unstaking. 
Also, there was a secondary issue on the create transaction form. The view was set up to watch the value of `nativeToken` and set it as the top (selected) item in the currency list every time the value changed. This meant that for every successful poll, XRD would bump to the top, replacing whatever the user had selected. This issue has also been patched.

fix: show the selected currency in the conf modal

---

src/components/OtherTokenBalanceListItem.vue

This PR fixes an issue where the rri address wouldn't scroll with its other token balance.
https://www.loom.com/share/48dc7029c6c14080803e63f0597fcf2f

fix: make rri address scroll with token balance

---

.github/actions/mark-latest/action.yml
.github/actions/mark-latest/index.js
.github/workflows/release-latest.yml
package.json
vue.config.js
yarn.lock

This PR enables the latest builds based on commits to main while preventing the build process from conflicting with the release cycle that could be running in parallel.
On release of 1.2.0, we discovered an issue where `release-please` and `release-latest` were racing to provide packaged builds that would be linked with the official release.
This PR removes that race condition by using a custom action to mark the `release-latest` builds as 'latest'.  This custom action does this by modifying the `package.json` file.
This enables:
* `vue.config.js` updates the `html title` of the electron app to include the 'LATEST' flag.
* `vue.config.js` overrides the default release behavior, setting it to null (there's a combination of bugs and poor documentation in `electron-builder` on the correct …

chore: Enable Latest Builds

---

src/composables/useStaking.ts
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue

This PR updates three different views
1. The History view should show a loading indicator while the data is loading and only show "No transactions" when the sub resolves with no transactions
2. The Transaction view should show a loading indicator while the data is loading and only show "No tokens" when the sub resolves with no tokens
3. The Staking view should show a loading indicator in the sidebar while the data is loading
https://linear.app/township/issue/RDX-279/better-error-messages-for-slow-loading-history-send-and-stake-views

chore: Differentiate in the UI between loading data and the user having no data

---

src/components/OtherTokenBalanceListItem.vue

This PR changes what's being populated in the Title of each otherTokenBalance. It used to use the token symbol and is now using the token's name.
Before:
After:

chore: change tokenbalance identifier name to token name

---

src/App.vue
src/components/AppButtonCancel.vue
src/components/AppModal.vue
src/components/ErrorModalGeneric.vue
src/components/ErrorModalTransactionBuilding.vue
src/components/ErrorModalTransactionConfirming.vue
src/composables/index.ts
src/composables/useErrors.ts
src/composables/useTransactions.ts
src/composables/useWallet.ts
src/text/index.ts
src/views/Wallet/WalletTransaction.vue

This PR... 
- adds a reusable modal component that can be expanded upon for more standard errors across the app
- adds a new composable called `useErrors` that manages the list of errors the app has caught
- Displays an error to the user when building a transaction fails
- Displays an error to the user when finalizing a transaction fails

feat: Add error modals for generic and txn errors

---

src/components/OtherTokenBalanceListItem.vue

On a slow connection (current mainnet), I was receiving errors as the component attempted to load without data. This patch corrects that.

Fix: don't error on null/empty tokens

---

src/views/Wallet/WalletLedgerVerifyAddressModal.vue

When a user attempts to copy the non-active hardware account account number, we now show appropriate copy instead of the verify process. See video for details.
https://www.loom.com/share/bf3c3800d1b34d019daf8dc109b79d1d

feat: show copy when verifying non-active hw acct

---

src/components/StakeListItem.vue
src/helpers/explorerLinks.ts

This PR removes the ability to click on an invalid/exploitable URL. The tooltip hover effect has been removed as well, but open to thoughts on a custom tooltip text IF a URL exists, but the URL is invalid? @alexandreaco @staylorwr 
So far I've only found Validator URLs used on the Staking Page within Olympia. Let me know if it's being used elsewhere.
Right now we are only considering "exploitable URL's" as URL's that do not begin w/ `http://` or `https://`. The validation created will check specifically for these substrings to be at the beginning of URLs passed into it.
[Demo](https://www.loom.com/share/c665f14d5f664d32a75698ab60b43a56)
To spoof the "bad urls" since I'm not quite sure how to add custom Validators to test, I changed `computed` values as seen in the Loom video
Spoof cases
- …

chore: only validated Validator URLs are links, otherwise displayed as plain text.

---

src/background.ts

This PR does two small things:
- Currently, if a user clicks the `X` button on OS X only, and then put their computer to sleep they'll return a crash report. This fix prevents that crash from occurring. We were attempting to reset state in a window that did not exist after being closed, we prevent that from occurring.
- It also disables the maximize button which was causing confusion among users.

fix: prevent crash on sleep and hide max button

---

src/views/Settings/SettingsSelectNode.vue

When a user submits a custom node URL, we should first trim their entry before comparing for uniqueness or adding the URL.
[See a demo](https://www.loom.com/share/9322f5c00a21426bb0f4b02172ff9a09)

fix: custom node URL inputs should be trimmed

---

src/views/Wallet/WalletConfirmTransactionModal.vue

This PR prevents User from closing the Transaction modal by hitting Escape. It gives a false sense that the tx has been cancelled when in fact it hasn't. For hardware wallet, the tx can still be cancelled via declining on said hardware wallet. On Olympia, the tx can't be cancelled after Confirm button has been hit(this isn't new behavior).
I've created a function which removes an event listener upon hitting the Confirm button. Using this lifecycle, should I remove the `windows.removeEventListener()` from `onUnmounted` hook, since it should be disabled by then?

chore: disable Escape event listener earlier in lifecycle

---

.gitignore
README.md
dev-app-update.yml.sample
src/updater.ts

Potentially resolves an issue where electron updater is expecting an `app-update.yml`.

fix: remove references to dev-app-update.yml

---

src/components/BigAmount.vue

[Demo](https://www.loom.com/share/ff8a4d37fb814e47a857be49df8033d7)
This PR addresses the issue of when tooltip amounts of 3rd party balances are clipped by its container. Here is an example.
Before:
After: 
As you can see here, the first digit is clipped. This occurs due to tooltips being based on the center of the display number. With the display number being a low amount of digits, the tooltip begins farther on the left as opposed to other longer digit numbers.
To handle this, we are offsetting the margin for numbers with digits lower than 4. In the demo, we are using an extreme case of a 1 digit display balance number, and a 17 digit tooltip balance. We don't want this offsetting to occur on long digit display balances either, so we are using a conditional to offset specifically low …

fix: add conditional margin to avoid tooltip from being clipped by parent divs

---

src/composables/useTransactions.ts
src/composables/useWallet.ts
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue
src/views/Wallet/index.vue

This PR changes the behavior when a user rejects the signing of a transaction. For some reason we had implemented a function to essentially reset the user's hardware account, and prompt them to reconnect their hardware wallet. I've racked my brain, and can't explain for the life of me why we'd do that. I think this was a poor decision made during the large refactor and not appropriately revisited.
This fixes an issue that surfaced when attempting to send a transaction after rejecting a transaction. The wallet would enter a confused state - thinking it had no hardware wallet connection, when in fact it does.
[Loom Demo.](https://www.loom.com/share/fd4c14ef075a425fab9a36d67a3b6853)

fix: do not reset hardware account on sign reject

---

src/components/BigAmount.vue

[Demo](https://www.loom.com/share/187fe731933947c4988db16ff7efab80)
This PR changes Tooltip styling so tooltip will begin from leftmost part of the div. Previously we were running a conditional where only specific amount of digits will offset the tooltip away from the left, but now we will render the tooltip relative to div.

chore: adjust tooltip balance styling

---

src/components/PasswordField.vue
src/views/CreateWallet/CreateWalletCreatePasscode.vue
src/views/Home/HomeEnterPasscode.vue
src/views/Settings/SettingsResetPassword.vue
src/views/Settings/SettingsRevealMnemonic.vue

This PR introduces a `PasswordField` that extends the existing `FormField` and adds some additional logic to detect if either capslock is pushed, or if the input has caps enabled (to handle cases where a user enables caps lock in a separate window and then returns to the wallet).
https://www.loom.com/share/a070f7e403b14641a5e7f0b7730dda4d

chore: warn of caps lock in password inputs

---

src/text/index.ts
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletStaking.vue

[Demo for Sending/Staking](https://www.loom.com/share/a91f49fb5c0d4e178a5c51edd8cc078d)
[Demo for Unstaking & the lack of this warning message](https://www.loom.com/share/b2823102ee4f4b9e94f16625a5180eaf)
This PR will throw a warning to the User to let them know upon this transaction, their total XRD balance will be < 10 XRD. This message applies to Staking and Sending Tokens, but not Unstaking.
Warning message should apply to case where User sends NON XRD token as well, since there is still a `Transaction Fee` involved.
- Sending/Staking XRD Calculation:
-  Total XRD - XRD Amount Input(to stake or to send) - Transaction Fee > 10?
- Sending NON XRD Calculation:
- Total XRD - Transaction Fee > 10?
- Unstaking should never trigger this warning, even if...User has 2 XRD and is unstaking 1 …

chore: show warning when txn brings total XRD < 10

---

src/components/StakeListItem.vue
src/composables/useStaking.ts
src/text/index.ts
src/views/Wallet/WalletStaking.vue
tailwind.config.js

[Demo](https://www.loom.com/share/3bb6bef1a1fa4bdab4a01a1a529034a9)
This PR gets the Top 100 Validators, and checks against User's current stake positions. If any positions are outside of the Top 100 Validators, we will indicate by showing a `no emissions` text on validator.
Demo video mocks a Top 28 Validators list, and I want to show that by changing the value to 27, the 28th Validator will show the `no emissions` text.

chore: add indication to current stakes list

---

src/components/AppSelect.vue
src/components/MnemonicDisplay.vue
src/components/MnemonicInput.vue
src/helpers/mnemonic.ts
src/text/index.ts
src/views/CreateWallet/CreateWalletEnterMnemonic.vue
src/views/CreateWallet/CreateWalletViewMnemonic.vue
src/views/CreateWallet/index.vue
src/views/RestoreWallet/RestoreWalletEnterMnemonic.vue
src/views/RestoreWallet/index.vue
src/views/Settings/SettingsRevealMnemonic.vue

Users can now select seed length options from a dropdown when creating and restoring a wallet s.
Creating a wallet: https://www.loom.com/share/685ec18951cb4cf7b2d06ef2a6ee7780
Restoring a wallet: https://www.loom.com/share/e22d659f81bb4fc7b17464fa79af24de

feat: Allow users to enter 12, 18 and 24 phrase mnemonics

---

package.json
src/components/OtherTokenBalanceListItem.vue
src/composables/useNativeToken.ts
src/composables/useStaking.ts
src/composables/useTransactions.ts
src/composables/useWallet.ts
src/helpers/network.ts
src/views/Home/index.vue
src/views/Settings/SettingsResetPassword.vue
src/views/Settings/SettingsResetPin.vue
src/views/Settings/SettingsRevealMnemonic.vue
src/views/Wallet/WalletStaking.vue
yarn.lock

Using https://github.com/radixdlt/radixdlt-javascript/pull/177 as a base for the SDK, I was able to work through a few more type changes.  We have the following errors to content with: 
**hardwareWalletConnection**:
https://github.com/radixdlt/olympia-wallet/blob/st/keystore-changes/src/composables/useWallet.ts#L269
```
ERROR in src/composables/useWallet.ts:269:50
TS2345: Argument of type '{ keyDerivation: HDPathRadixT; hardwareWalletConnection: Observable<Readonly<{ getVersion: () => Observable<Readonly<{ major: number; minor: number; patch: number; equals: (other: Readonly<...>) => boolean; toString: () => string; }>>; ... 4 more ...; makeSigningKey: (path: HDPathRadixT, verificationPrompt?: boolean...' is not assignable to parameter of type 'Readonly<{ keyDerivation: …
```

Keystore changes

---

src/actions/electron/data-store.ts
src/actions/vue/data-store.ts
src/background.ts
src/composables/useWallet.ts
src/electron-store/migrations.ts

this PR:
- stores the address of the latest account selected on account switch
- switches accounts when the latest account saved is loaded and doesn't match the currently active account
https://www.loom.com/share/60ad0c46123f4c0297b53baf9847d781

chore: remember last selected account

---

src/views/Settings/SettingsResetPin.vue

This PR updates a password field in the pin reset page.

fix: add missing password field to pin reset page

---

src/views/Home/HomeEnterPasscode.vue

The password fields are wrapped in a div to help display the caps lock warning, and as a result the id was being placed on that parent div and not the actual input. The query selector fixes that.

fix: password field on login should auto focus

---

src/actions/electron/data-store.ts
src/actions/vue/data-store.ts
src/assets/tailwind.css
src/background.ts
src/text/index.ts
src/views/Home/HomeTos.vue
src/views/Home/index.vue

This PR adds the TOS to the home screen, displaying it if it has not been accepted yet. Once it's been accepted, the value is added to the store; if the terms ever need to change, we should be able to add a migration to reset that field to 'false' for all users again, forcing them to accept the new terms before use.
Below are a few screenshots of the implementation:

chore: add legal terms to home view

---

src/components/StakeListItem.vue
src/text/index.ts

chore: update current stakes list warning styling

---

src/composables/useTransactions.ts

Co-authored-by: Alex Stela <xstelea>
From @xstelea 
I refactored watchUserDidConfirm and moved it outside of useTransactionsfunction.
In the confirm transaction modal there are at least 3 components rendered that import and use useTransactions , and each is subscribed to userConfirmation. This causes multiple subscriptions to trigger when the user confirms the transaction, resulting in multiple finalize& submit requests

Transaction subjects

---

src/components/AppSelect.vue
src/text/index.ts
src/views/RestoreWallet/RestoreWalletEnterMnemonic.vue
src/views/RestoreWallet/index.vue

- fix: Prevent select dropdown from opening on enter press
- fix: Prevent mnemonic from submitting before all fields are present
- fix: Cleanup restore wallet enter mnemonic UX

fix: Cleanup restore wallet enter mnemonic UX

---

src/components/ActionListItemTransferTokens.vue
src/components/TransactionListItem.vue
src/text/index.ts

This PR makes some small UI updates to how we display edge cases actions in the history view.
1. For transactions with an empty actions array, we display "Unknown transaction." This most often occurs when we return legacy self-transfers
2. For transactions with multiple actions, i.e. complex transactions, we display "Complex transaction" and tell the user if some of the actions were filtered out because they don't relate to the current active address
See notes in linear for reference https://linear.app/township/issue/RDX-314/sdk-upgrade-history

Improve display of complex actions in history

---

src/App.vue
src/components/ErrorModalApi.vue
src/composables/useErrors.ts
src/composables/useTransactions.ts
src/text/index.ts
src/views/Wallet/WalletTransaction.vue

This PR adds an additional error modal specifically for handling API errors. For known errors, a friendly message is displayed; otherwise, a detailed modal with the error message, trace id, and contact email is displayed.
Examples:

chore: api error handling

---

src/text/index.ts
src/views/Wallet/WalletConfirmTransactionModal.vue

This PR fixes a bug where not all relevant transaction states were showing the "confirm and sign" modal when sending an encrypted message. it also fixes a bug where you could end up with multiple modals because we were missing if-else statements.

fix: Tell user to confirm on ledger device at all relevant steps

---

src/composables/useWallet.ts
src/helpers/network.ts

New Wallets or wallets without a custom node url should default to mainnet,  we had changed this value while the SDK / API were being updated.  This can be restored to it's original value now that the mainnet gateway is live.

fix: Default to Mainnet for new wallets

---

src/helpers/network.ts
src/views/Wallet/index.vue

This PR makes two small changes:
* The network helpers used for the default list of available gateways was incorrect
* The case of the string representing the activeNetwork has changed in the latest SDK so the test network warning was showing even when connected to mainnet.

fix: network versions

---

src/components/PasswordField.vue

This PR updates the password field to clear the caps lock warning when the field loses focus. This helps with screens where there are multiple password fields (ie password update, where you have current, new, and confirm new password fields); previously each individual field would track the caps lock status independently, resulting in some odd looking states. Now, the caps lock warning clears when you change fields and shouldnt display in multiple places.

Fix: clear caps warning on pw field on focus lost

---

src/components/ErrorModalGeneric.vue
src/text/index.ts
src/views/Home/HomeEnterPasscode.vue

This PR fixes an issue where we weren't handling an error on login resulting from being unable to connect to custom nodes, ie https://coinwrap.co, and the error was instead being treated as an invalid password error. The user should now get sent to the settings page with an error modal if they provide a valid password but are unable to connect to their current custom node.
https://www.loom.com/share/d4b83ef722394ead95a9757a9f55fa80

fix: send user to settings page if unable to login

---

src/composables/index.ts
src/composables/useHistory.ts
src/composables/useTransactions.ts
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue
src/views/Wallet/index.vue

This PR isolates the logic for the History UI into an independent composeable that manages a single, interval driven subscription.
There have been a significant number of recent performance problems specifically with the history page.  We suspect that this may be due to rxjs subscriptions that were not completely cleaned up on route transitions or pagination logic.  
This works also replaces the `radix.transactionHistory` call with a collection of rxjs manipulations with a single api `radix.ledger.transactionHistory` call that returns a promised result on a `interval` subscription.  This should help eliminate the internal side effects of the main `radix` subscribe-ables and cleans up the responsibility of watching for changes in dependent values by isolating those responsibilities to the …

fix: Isolate History Logic

---

src/text/index.ts
src/views/Wallet/WalletTransaction.vue

This PR updates the wallet to exclude hidden token from the dropdown list when sending tokens.
I attempted to take a loom, but it didn't actually show the dropdown in it! So here's some screenshots instead. Note that `wibble` is not an option in the send tokens dropdown while the token is hidden in the 'token' (previously named 'balance') tab.

chore: hide hidden tokens from send dropdown

---

src/composables/useHistory.ts
src/text/index.ts
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletLedgerVerifyDecryptModal.vue

This PR updates the wallet history page to include a modal when:
1) the current active account is a hardware account, and
2) when the wallet is waiting on the hardware ledger to confirm decryption
See loom demo:
https://www.loom.com/share/526c0941717d46adb1c7df48948f132e

chore: add ledger decrypt message modal

---

src/composables/useTransactions.ts

This PR updates the error shape that's returned when disconnecting a hardware ledger to include the category attribute that was added in this other PR https://github.com/radixdlt/olympia-wallet/pull/438/files

fix: Update disconnect hardware device error shape for new component

---

src/components/ActionListItemStakeTokens.vue
src/components/ActionListItemTransferTokens.vue
src/components/ActionListItemUnstakeTokens.vue
src/components/HiddenTokenBalanceListItem.vue
src/components/OtherTokenBalanceListItem.vue
src/components/StakeListItem.vue
src/components/TokenSymbol.vue
src/components/TransactionListItem.vue
src/views/Wallet/WalletOverview.vue

[Demo](https://www.loom.com/share/5cae67112bad4a1ea17d073a1411919a)
This PR adds the feature of clicking on any token symbol Olympia-wide and being directed to respective token's Explorer page. We are also exposing the token RRI by hovering over the token symbol.
We've adjusted `TokenSymbol.vue` to take required attributes `rri`, `symbol`, and `hasGreyBackground`. We initially wanted to pass the entire `Token`, but it seems that we're sometimes passing an `Action`. It may be better to pass these two strings `symbol` and `rri`, which both entities own as opposed to having the component figure out which of the Types it's extracting data from.

fix: have all token symbols clickable and redirects to Explorer token page

---

src/components/ErrorModalGeneric.vue
src/text/index.ts

While we wait for better network connectivity error messages from the SDK, we are pinging the network every 10 seconds and showing users a warning if the network cannot be reached. In this PR, we are removing the cancel button and added some warning text encouraging users not to re-attempt transactions that may have succeeded before connection was lost. Removing the cancel button will prevent users from continuing to use the app when it's not connected to the network.

chore: Present users with a better error experience if they loose network connectivity

---

src/components/StakeListItem.vue

We already had this feature in the explorer. Now, we will also hide recent uptime for validators not in the top 100 for the wallet.

chore: Don’t show validator uptime for validators below top 100

---

src/composables/useHistory.ts
src/composables/useWallet.ts
src/views/Wallet/WalletHistory.vue

[Demo showcasing freely switching between accounts on History Page](https://www.loom.com/share/8dcd1a5547aa491f8ead3949c45e4236)
Joint effort by @saminakh & I! https://github.com/radixdlt/olympia-wallet/pull/454/files
This PR updates account switching logic in `useHistory` composeable, and updates the `account` value before resetting History Page transactions while switching accounts. We're also making sure to restart polling of subscriptions properly upon account changing.
The issue previously was that the incorrect `publicKey` was being used from the incorrect account, while it seemed like the `to_address` public key and `from_address` public key was correct.
We're also now handling hardware-account-specific account changing. Previously, certain modals such as decrypt on hardware device …

fix: decrypt errors while switching accounts on history page

---

src/composables/useTokenBalances.ts
src/composables/useWallet.ts
src/views/Settings/SettingsTokens.vue
src/views/Wallet/WalletOverview.vue
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue

This PR takes a fresh approach to solving the active account and subscription issues on the balances view. Thanks to @SK-Sam and @staylorwr for all of the brainstorming. The original bug described a flash on the balances screen with the wrong account balances appearing before the real active account balance appeared. It turns out, this was an issue on all views that show token balances and allow for account switching from the sidebar. 
This PR fixes the bug on the following pages. At the time of posting, we still need to fix the settings > hidden tokens page

fix: Correctly load token balances when switching active account

---

src/views/Wallet/WalletStaking.vue

See [original error ](https://www.loom.com/share/3d2b142dcc7c49d29f4b618592e5bc9b) here.
When in the staking view, if a user chose to stake / unstake without preemptively filling out the amount form field, a `valid amount` error would occur, and would not disappear until the user clicked out of the form component (IE on `blur`). The chances of a user filling out the amount form field before choosing whether to stake or unstake were unlikely so the error no longer appears. 
This was caused by the stake/unstake buttons triggering a validation function that checks the values of both the automatically populated `validator address` and the `amount` value. The validation assumes that a value will be passed for `values.amount` and raises an error when the amount is left undefined. Now if the …

fix: staking amount error prematurely displays

---

src/views/Wallet/WalletStaking.vue

[Extension of this pull request ](https://github.com/radixdlt/olympia-wallet/pull/466)
We found an additional premature form field error popping up when a user clicks into either 'address' or 'amount', clicking out of the form field component entirely causes an error message to appear even when `add/reduce stake` is clicked. An easy way around this was to disable validation on blur - and as an extra level of protection, add `validateOnInput = true` to the address field.
📸 - *notice at end I delete a character from the address and the error message appears*

fix: staking prematurely displays error

---

src/composables/useHistory.ts
src/text/index.ts
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletLedgerDisconnectedModal.vue

When a user is logged in to a hardware account, and the ledger device is disconnected, unhandled console errors would appear when the user tried to decrypt an encrypted message on the transaction history page. Now when a user encounters this situation, an error modal will pop up and inform the user of an error that is most likely occurred from a disconnected ledger.
[Here is an example of the pop-up in action.](https://www.loom.com/share/f80e68f7b041486d9548a54121c9ddfc)
📸📸📸📸

fix: display error modal on failed hardware decryption

---

src/views/Wallet/WalletTransaction.vue

This bug happens on the off chance of two (or more) tokens having the same name and different rris. the app incorrectly grouped them in the token select dropdown. This prevents the user from selecting the second token with the same symbol and won't display an accurate amount in the amount placeholder. 
The bug was caused by the currency dropdown selecting and passing on the `rri.name` for each currency, which is a less detailed string ID of the token. Changing the dropdown values `rri.toString()` passed along a more specific string ID, explicitly differentiating tokens with the same name but different rris. 
*in this video, I have two tokens named `5H5M3U` with separate rris - you can see the amount placeholder change on token change, indicating it is in fact choosing between two …

fix: bug tokens with same symbols are incorrectly grouping 

---

package.json
src/components/BigAmount.vue
src/composables/useTransactions.ts
src/text/index.ts
src/views/Wallet/WalletConfirmTransactionModal.vue
src/views/Wallet/WalletStaking.vue
yarn.lock

[Demo](https://www.loom.com/share/3aaa659c442e4e2c9efa2afdcd6d18d3)
This PR implements a new button which allows User to unstake 100% of their XRD from validators. We add extra logic in order to switch between "Max Unstake Mode" and regular unstake mode.
No unique step has to be taken to unstake via Max Mode, User simply hits the same `Request Unstake` button as I was able to implement a function that decides which unstake mode to use.

chore: Add max button for unstaking

---

CHANGELOG.md
package.json

* feat: Handle incomplete hardware wallet signature  by @SK-Sam in https://github.com/radixdlt/olympia-wallet/pull/438
* feat: Add disclaimer to wallet recovery by @SK-Sam in https://github.com/radixdlt/olympia-wallet/pull/442
* Only show hardware modal when in hardware transaction flow by @alexandreaco in https://github.com/radixdlt/olympia-wallet/pull/437
* chore: hide hidden tokens from send dropdown by @saminakh in https://github.com/radixdlt/olympia-wallet/pull/446
* chore: add ledger decrypt message modal by @saminakh in https://github.com/radixdlt/olympia-wallet/pull/443
* fix: Update disconnect hardware device error shape for new component by @alexandreaco in https://github.com/radixdlt/olympia-wallet/pull/452
* fix: have all token symbols clickable and redirects to Explorer token …

chore: Release v1.3.3

---

src/actions/electron/data-store.ts
src/actions/vue/data-store.ts
src/background.ts
src/composables/useWallet.ts
src/electron-store/migrations.ts
src/text/index.ts
src/views/Wallet/WalletSidebarAccounts.vue

The wallet.json schema now features a `hardwareDevices` block which will allow us to store multiple ledgers (their identified by their first derived account address). Along with multiple accounts per wallet. The schema looks like the following 
```JSON
"hardwareDevices":[
{
"name":"tdx1qsps3cs7dkhhpgrvulm32222cgrekn99d9sqke48e0vw0echs9w2hysn46mcy",
"addresses":[
{
"name":"tdx1qsps3cs7dkhhpgrvulm32222cgrekn99d9sqke48e0vw0echs9w2hysn46mcy",
"address":"tdx1qsps3cs7dkhhpgrvulm32222cgrekn99d9sqke48e0vw0echs9w2hysn46mcy"
},
{
"name":"...",
"account":"...."
}
]
}
```

feat: update wallet.json schema to accept multiple accounts per ledger WIP 

---

src/actions/vue/data-store.ts
src/composables/useWallet.ts
src/electron-store/migrations.ts
src/services/_types.ts

devices addresses dont need names, handled by existng account naming

Remove device address name

---

src/actions/electron/data-store.ts
src/actions/vue/data-store.ts
src/composables/useWallet.ts
src/text/index.ts
src/views/Wallet/WalletDeviceEditName.vue
src/views/Wallet/WalletHideAccountModal.vue
src/views/Wallet/WalletNewDevicePopup.vue
src/views/Wallet/index.vue

The title explains this one for the most part. In the addition to multiple devices, my original method of saving renamed devices had a bug that came to the surface. Also when a new account is made with a new device, a small popup modal will appear alerting the user that a new device has been connected and saved.

Feat: fix renaming device functionality and add new device popup 

---

package.json

The store migrations won't run on latest because it's still locked to the same version.

Fix Latest builds by bumping the version

---

src/actions/vue/data-store.ts
src/composables/useWallet.ts
src/views/Wallet/WalletSidebarAccounts.vue

This PR allows for the user to toggle "collapse" a cluster of accounts. All software accounts and / or all accounts under and individual hardware wallet can be collapsed and re expanded.

feat: toggle show hide software hardware accounts

---

src/views/Wallet/WalletStaking.vue

[See Linear Issue RDX-358](https://linear.app/township/issue/RDX-358/dust-prevention-unstaking)
This PR prevents the user from leaving “dust” in their wallet if they manually input the unstake amount instead of clicking the max button.  When a user presses the ```reduce stake``` button, the validatorAddress ref is assigned the value of the validator.  A function was added that checks if the difference between the users input and the max unstake amount is within ```0.000001``` only if there is an address in the validator address field above it.  If it is, this triggers the same behavior as if the user had pressed the max button, utilizing the full unstakable amount.  
[Watch Loom Demo Walkthrough](https://loom.com/share/f15fb724a2b84ef08dd287022dfc7b35)
In WalletStaking.vue
- In the …

feat: automatically turn on max unstake mode based on user input

---

.github/workflows/release-latest.yml
.github/workflows/release-main.yml

The notarization of Mac OS builds (currently only the latest builds, but I'm assuming the same problem will arise from a proper release) fail because the notarization system now requires the team id associated with the app and certificates.
You can see an example of this error [here](https://github.com/radixdlt/olympia-wallet/runs/6489331794?check_suite_focus=true).   You can see this [gist](https://gist.github.com/fbaiodias/ec08ee0141e06a98470230e564220cfa) for a related issue and [the electron-build-notarize](https://github.com/karaggeorge/electron-builder-notarize) repo for how the environment values are specified.  @russellharvey We'll need to add this variable as a repo secret value.  I'll follow up directly to make sure the value gets set.

chore(ci): Fix Mac OS Notarization by providing the apple team id

---

scripts/notarize.js

Validated locally that this change correctly allows the app to notarize again.

chore: notarize needs the team id

---

src/text/index.ts
src/views/Wallet/WalletStaking.vue

This PR adds a notification to the user when `max unstake mode` has automatically been enabled if the amount they input is  within `0.000001` of the max staking amount.  This notification is not displayed if the user pressed the `max` button as that is intentional.
[See Linear Issue RDX-391 Here](https://linear.app/township/issue/RDX-391/notify-when-max-mode-enabled)
[See Figma File Here](https://www.figma.com/file/lNzG5jBt1P9yatkGbWjrlk/Radix-Wireframe-V1?node-id=4270%3A68504)
https://user-images.githubusercontent.com/83678228/169533405-91df34aa-1b02-4685-af2a-b702d7714319.mov
In `WalletStaking.vue`
- I added a div that is conditionally rendered if `showMaxUnstakeNotification` is `true`.  The div contains the svg from the Figma file as well as a span displaying the notification message. …

feat: notify user when max mode enabled

---

package.json
src/components/TransactionListItem.vue
src/components/TransactionMessage.vue
src/helpers/message.ts
src/text/index.ts
src/views/Wallet/WalletStaking.vue
yarn.lock

This pull request switches from the SDK provided in 4.0.15 to 4.0.17.  The new SDK provides the raw hex-encoded message from the API.  The functionality was copied from the explorer into the wallet. Now, the `TransactionListItem` component can use the raw message and determine if it is plain text or encrypted.  If it is plain text the plain text is displayed initially.  If the message is encrypted a button is displayed that the user can click to reveal the decrypted message.
[See Linear Issue #RDX-388 Here](https://linear.app/township/issue/RDX-388/encrypted-message-tomfoolery)
I copied the functionality from the explorer in [this PR](https://github.com/radixdlt/explorer/pull/97)
https://user-images.githubusercontent.com/83678228/170314521-d22fd06b-8dce-439f-aa38-ae30ac658aff.mp4

feat: use new SDK to determine transaction message encryption status

---

src/views/Wallet/WalletTransaction.vue

This PR addresses an issue in the wallet transaction view. We were originally resetting the selected currency input to XRD every time `nativeToken` or `tokenBalances` were loaded. This ensures the value is not reset after the initial load.

fix: don't set XRD by default multiple times

---

src/composables/useStaking.ts

The issue - In order to keep staking/unstaking list items content up to date the data was refreshing every ~15 seconds, causing the `loadingStakes.value`  & `loadingUnstakes.value` Refs to be set to true, in turn having the list items unmount and a loading wheel take its place. this gave off the illusion of a flickering side panel. 
The solution - Continue to refresh the staking data every 15 seconds, but in the function `fetchStakesForAddress` no longer set the `loadingStakes.value`  & `loadingUnstakes.value` to false for each refresh, since those two Refs default to true, the loading wheel will render on initial mount but not on each individual refresh. 
[Loom video here. ](https://www.loom.com/share/c02d25d6f0c7478dac51bf35f7222276)

fix: stake list items no longer flickering on refresh 

---

src/components/AccountListItem.vue
src/components/AccountListPreview.vue
src/components/HardwareAccountListItem.vue
src/views/Wallet/WalletSidebarAccounts.vue

This PR just makes a couple small tweaks that came up during QA.
- Removes a double divider line when there are no hardware accounts.
- Slightly widens the account name labels to provide for longer titles.
Before:
After:

Chore: Minor UI Tweaks

---

src/text/index.ts
src/views/Wallet/WalletStaking.vue

This PR checks if the `unstake` amount the user typed is greater than the `max-unstake` amount available.  If so, a notification is displayed informing the user that the amount they typed was rounded down to the `max-unstake` amount available, since you cant unstake more than you have.  Before it only checked if the `minDifference` amount was <=`0.000001` which did not account for any negative values.  If the `minDifference` is negative that means the user tried to `unstake` more than they have available.  If `minDifference` is positive, then the user entered a number lower than the `max-unstake` amount and a notification should only be displayed if this value is <= `0.000001`.
[See Linear Issue RDX-397 Here](https://linear.app/township/issue/RDX-397/user-not-accurately-notified-of-unstake …

feat: add check for amount greater than max

---

src/composables/useHistory.ts
src/composables/useWallet.ts
src/views/Wallet/WalletDisconnectDeviceModal.vue
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletLedgerDisconnectedModal.vue
src/views/Wallet/WalletLedgerInteractionModal.vue
src/views/Wallet/index.vue

Removed any rendering of the original boilerplate ledger error modal and am now rendering a prettier modal when a ledger-specific action results in an error.

fix: multiple error pop ups when the ledger

---

package.json
yarn.lock

There were lots of security patches available for tooling, so I went ahead and ran `yarn audit` and then ran `yarn-audit-fix` to fix many of them.

chore: Upgrade dependencies based on yarn audit

---

src/views/Wallet/WalletNewDevicePopup.vue

The old alert pop-up was being clipped by the accounts list side nav and wasn't styled like a _speech bubble_. This fix refactors the pop up to look more like the figma styling.

chore: improve new ledger device pop up

---

src/views/Wallet/WalletStaking.vue

This PR adds a short circuiting conditional inside the `compareToMaxUnstakeAmount` function if the user is on the `Stake Tokens` view.  Previously, the same behavior is displayed on the `Stake Tokens` view that should only show when the user is on the `Unstake Tokens` view.  This is happening because the form inputs are reused for both views therefore the validation also occurs no matter what view the user is on.  Since there is no `max` functionality on the `Stake Tokens` view this functionality should be skipped.
[See Linear Issue RDX-399 Here](https://linear.app/township/issue/RDX-399/unstake-tokens-notifications-show-on-stake-tokens-view)
https://user-images.githubusercontent.com/83678228/171699773-a51a05b2-abb3-4cee-b896-d82c9d08ce87.mp4 …

fix: short circuit comparing amount functionality if on stake tokens view

---

src/views/Wallet/WalletHistory.vue

Navigating between active accounts on the history page was leaving the transaction subscription active for the old active address and also generating a new sub for the old one.  This PR cleans up those subscriptions for both data consistency and flickering UIs

fix: History page was leaving history subscriptions active when changing active addresses

---

package.json
src/actions/electron/hardware-wallet.ts
src/components/AccountListItem.vue
src/components/AccountListPreview.vue
src/components/ClickToCopy.vue
src/components/HardwareAccountListItem.vue
src/composables/useWallet.ts
src/views/Wallet/WalletHistory.vue
src/views/Wallet/WalletOverview.vue
src/views/Wallet/WalletSidebarAccounts.vue
src/views/Wallet/WalletTransaction.vue
yarn.lock

https://www.loom.com/share/f9e3042553144e07af3aceb057ee5659
Depends on the changes in https://github.com/radixdlt/radixdlt-javascript/pull/202
This PR cleans up two edge cases where the SDK / Wallet were depending on `wallet` state to correctly derive and message the correct ledger device.
**Verify HW Address**
From my understanding of the SDK, in the above PR, I've updated the wallet functionality for displaying the address on the ledger device to no longer observe and pipe through the `activeAccount` observable.  On major wallet / hw account / active account changes, this caused the verify function to send three+ equivalent, duplicate messages through the `sendAPDU` tunnel.  
**Deriving new HW Devices**
It seems that another side effect of this observable magic is that hw accounts would …

Verify Address and Initial HW wallet bugs

---

src/views/Wallet/WalletStaking.vue

This PR stops the user from pressing the `max` button if they have not first entered a `validator address`.  Previously the user could press the `max` button at any time which triggers the state of the `Request Unstake` button to change from disabled to active. As a result, the user can then click the `Request Unstake` button which causes an error, but the user isnt aware, because it doesnt provide any feedback to the user.  Now the state of the `max` button is controlled based on whether the user has entered a value in the `validator address`.  Once an address is entered, the disabled styling of the `max` button is removed.
[See Linear Issue RDX-400 Here](https://linear.app/township/issue/RDX-400/max-unstake-button-should-be-disabled-if-no-validator-address)
In `WalletStaking.vue`
I used …

fix: stops user from pressing max without entering a validator address

---

src/actions/electron/data-store.ts
src/actions/vue/data-store.ts

This PR revises the deletion process so the entire 'wallet.json' file isnt cleared when you delete/restore a wallet.  The 'wallet.json' file holds information about a users wallet such as if they have accepted the 'terms of service'.  Previously, this entire file was cleared which left no memory if whether or not the user has already accepted the terms of service.  As a result, after deleting/refreshing a wallet the terms of service would appear after refresh.  Now, the 'acceptedTos' value is preserved, so when the 'wallet.json' file is cleared, this 'acceptedTos' value is immediately added back to 'wallet.json'.  Whenever a user deletes/restores a wallet, the app now remembers that the user has accepted the terms of service so it is not shown, the enter password view is shown instead. …

fix: save needed value in wallet deletion process

---

src/helpers/validateRadixTypes.ts
src/validations.ts
src/views/Wallet/WalletStaking.vue
src/views/Wallet/WalletTransaction.vue

To reproduce the bug, try to enter `11.111111111111111111` when sending the transaction.
This gets converted to `11111111111111110000` attos, while should be sent as "11111111111111111111".
Looks like this fixes the leftover dust when unstaking too.

fix: Proper precision for user-entered amounts.

---

src/views/Wallet/WalletStaking.vue

This PR updates the app to handle the user-entered amount as a `string` rather than a `number`.  The recent change from [this PR](https://github.com/radixdlt/olympia-wallet/pull/455#event-6798032238) handles precision loss. As a result the current build of the app failed, because it still used the amount as a number.  With this change, there is no longer an error upon building the app and I am able to complete a transaction as expected.
[See Linear Issue RDX-403 Here](https://linear.app/township/issue/RDX-403/update-function-to-use-amount-as-string)
In `WalletStaking.vue`
Inside the `compareToMaxUnstakeAmount` function the `values.amount` was first parsed as a Number and then passed as the parameter to the `safelyUnwrapAmount` function.  I removed this parsing, so the original string is …

fix: update function to pass in amount as string

---

src/text/index.ts
src/views/Wallet/WalletLedgerDisconnectedModal.vue

This PR changes the error message for `Ledger Device Disconnected` modal to be more descriptive.  I added a `disconnectedContent` property to the `index.ts` file in the text folder.  Previously, the error message displayed `Unable to decrypt message` when the user attempted to copy the address for a disconnected ledger.
[See Linear Issue RDX-405](https://linear.app/township/issue/RDX-405/fix-error-message-when-ledger-isnt-connected)

fix: update error message when ledger is disconnected

---

src/background.ts

Latest has a regression where we're missing two files, causing the background.ts boot to fail.

fix: Remove undefined functions

---

src/composables/useWallet.ts

Now the naming structure for ledger devices and their associated accounts will be formatted as followed upon creation...
```
- Ledger 1
- Hardware Account 1
- Hardware Account 2
- Hardware Account 3
- Ledger 2
- Hardware Account 1
...
```
Names can still be changed and updated as normal.

feat: rename and update new hw accounts

---

src/components/layout/WalletLayout.vue
src/composables/useWallet.ts
src/views/Wallet/WalletTransaction.vue

This PR adds another conditional to the 'wallet-ledger-interaction-modal' so that the 'deriving account' modal isnt showing if the user has initiated a send tokens transaction.  
This may be a fix for [Linear Ticket RDX-440](https://linear.app/township/issue/RDX-440)

fix: deriving account modal showing during transaction

---

src/composables/useWallet.ts

Reverts an earlier change that was introduced while debugging occasional
duplicate ledger messages [solved in
radixdlt-javascript#203](https://github.com/radixdlt/radixdlt-javascript/pull/203).
If the ledger falls asleep, the wallet should be able to reconnect to it.
**Steps to replicate**
1.  Connect a ledger and send a transaction from that account
2. Let the ledger fall asleep by waiting
3. Reactivate the ledger and reenter your pin
4. Send another transaction from a ledger account, if fixed it will work.

fix: Create a new HardwareWalletLedger on every ledger interaction

---

src/actions/electron/hardware-wallet.ts
src/composables/useWallet.ts

[Linear Issue](https://linear.app/township/issue/RDX-447)
This PR fixes a regression where if a user rejected a transaction on the ledger, the ledger would become unavailable until restarting the server.
This occurred because the connection was left open after an unexpected response from the device.

fix: Always close a ledger connection correctly

---

src/components/modals/WalletConfirmTransactionModal.vue
src/components/modals/WalletLedgerInteractionModal.vue
src/composables/useWallet.ts

This PR adds a conditional to the body of the 'Decrypting Message' modal that differentiates between a software and hardware account, so the the body is only shown when the active account is a hardware account.
Update:
I renamed the 'isSoftwareAccount' function to 'activeAddresIsSoftwareAccount' per Scott's suggestion and ensured the 'Submitting Transactions' modal is only shown at the end of a send tokens transaction, 
[See Linear Ticket RDX-448](https://linear.app/township/issue/RDX-448)

chore: add condition to decrypting modal body copy

---

src/views/Wallet/WalletStaking.vue

This PR adds an onChange handler 'checkForEmptyValidator' that checks if the user changed the validator input. Previously the user could fill both the validator and amount in, then if the validator address was removed, the 'Request Unstake' button did not go back to a disabled state.  As a result, the user could click this button and nothing would happen.
[See Linear Ticket RDX-450 Here](https://linear.app/township/issue/RDX-450)

fix: removing validator address doesn't disable 'Unstake' button

---

src/components/ErrorModalApi.vue
src/text/index.ts
src/views/Wallet/WalletTransaction.vue

- fix: ErrorModalApi is catching all generic errors
- fix: add an error message when a user has selected to encrypt a message but has not entered a message

fix: User should not be able to submit a transaction with a blank encrypted message

---

src/views/Settings/SettingsSelectDecimal.vue

This PR removes the disabled cursor from the radio buttons in the 'Display' tab.
[See Linear Ticket RDX-455](https://linear.app/township/issue/RDX-455)

fix: remove disabled cursor

---

src/background.ts

This PR fixes the bug when a user has been idle, but closed the app window.  Safeguards were add to ensure the window was still active, before the app tries to reload.
[See Linear TIcket RDX-460 for Demo Video](https://linear.app/township/issue/RDX-460)

fix: error thrown when user has been idle

---

src/components/modals/WalletLedgerInteractionModal.vue

This PR fixes the conditional that controls whether or not the `WalletLedgerInteractionModal` displays both title and body text.  An extension to the conditional was added if the `hardwareInteractionState` value is equal to `DERIVING`, the modal should not have any body text and only show `Deriving Account`.
See Loom Video in [linear ticket RDX-465](https://linear.app/township/issue/RDX-465)

fix: deriving account modal copy
