- src/views/Wallet/WalletHistory.vue
- src/views/Wallet/index.vue
[Loom Video](https://www.loom.com/share/b79724f6298f473197b565f4f0592fa0)
@alexandreaco what's the intended page size?  I'm assuming the original size of 100 was because of the lack of pagination.
> feat: Transactions can be pagianted.

- src/text/index.ts
- src/views/Wallet/WalletConfirmTransactionModal.vue
> style: Confirmation Modal should include a label for the PIN input

- src/components/TransactionListItem.vue
- src/views/Wallet/WalletHistory.vue
- src/views/Wallet/index.vue
Adds a little lock icon to encrypted messages.
> style: encrypted messages should show a lock

- src/views/Wallet/index.vue
I need to boot the explorer w/ the latest sdk pointed at sandpit to see if I can find a validator to test this logic, but this is the solution proposed in linear ticket.
> fix: Unstakes should include stakes from all epochs

- src/components/BigAmount.vue
- tailwind.config.js
https://www.loom.com/share/b1868bca05734a1ea3dcd5dfe7a26cd5
This PR also makes it much easier to add number format support for other than USA
> feat: update decimal display

- .github/workflows/release-please.yml
Currently we're building releases on every release-please run off of main.
> fix(CI): Unnecessary release builds

- package.json
- src/components/TransactionListItem.vue
- src/views/Wallet/WalletHistory.vue
- src/views/Wallet/index.vue
- yarn.lock
https://www.loom.com/share/b07eab2fde754b2ea1077fdc946d2189
> Encrypted Messages should be manually decrypted

- src/components/AccountListItem.vue
- src/views/Settings/index.vue
- src/views/Wallet/WalletHistory.vue
- src/views/Wallet/WalletOverview.vue
- src/views/Wallet/WalletSidebarAccounts.vue
- src/views/Wallet/WalletSidebarDefault.vue
- src/views/Wallet/WalletStaking.vue
- src/views/Wallet/WalletTransaction.vue
- src/views/Wallet/index.vue
- tailwind.config.js
﻿https://www.loom.com/share/b0d0fd5455d0413b9201b42d82a59096
> fix: Replace overflow-_-scroll with overflow-_-auto

- .github/workflows/release-please.yml
Include the output of the release please step of the release please job as an output of the job itself.
> fix: Release Please Output

- .github/workflows/release-please.yml
- package.json
- src/background.ts
- yarn.lock
I guess... it's this easy?  Release Please does a lot of work for us all ready.
> fix: Enable auto updates

- package.json
- src/router/index.ts
- src/views/Home/HomeLockedModal.vue
- src/views/Home/index.vue
- src/views/Wallet/WalletConfirmTransactionModal.vue
- yarn.lock
https://www.loom.com/share/5def09d8aac5426d99f7a46664093d0c
> feat: Too many PIN attempts should lock the wallet

- src/views/Account/AccountEditName.vue
- src/views/Wallet/WalletLedgerVerifyAddressModal.vue
- src/views/Wallet/WalletSidebarAccounts.vue
- src/views/Wallet/index.vue
- tailwind.config.js
https://www.loom.com/share/3366fdc9eab8469fba1750ffd914c782
This PR:
- fixes account renaming, which was broken in the rebase & merging of the ledger ux.
- fixes the sidebar transitions, broken by a ledger modal / rebase & merge.
> fix: Account Renaming broken from Ledger Epic

- package.json
- src/components/StakeListItem.vue
- src/store/_types.ts
- src/text/index.ts
- src/views/Wallet/WalletStaking.vue
- yarn.lock
Improve the design of the current stakes layout.
Also fixes the current logic by refactoring the separate lists of active
stakes and active unstakes into a list of positions, where a position
represents a validator and collects its list of active stakes and
unstakes.
It turns out the validator response does in fact return the recent
https://www.loom.com/share/991434fd0fa64c61967fb2f5d7eb527b
> fix: Current Stake Logic and UX

- src/actions/electron/data-store.ts
- src/actions/vue/data-store.ts
- src/background.ts
- src/text/index.ts
- src/views/Home/HomeEnterPasscode.vue
- src/views/Home/HomeForgotPassword.vue
- src/views/Home/index.vue
https://www.loom.com/share/ad55d9c22a044e13b2601e18ee49964b
> feat: password screen abort option

- src/components/BigAmount.vue
> fix: round half up, not truncate

- src/components/ButtonSubmit.vue
- src/components/PinInput.vue
- src/components/PinInputDigit.vue
- src/text/index.ts
- src/views/CreateWallet/CreateWalletCreatePin.vue
- src/views/Settings/SettingsResetPin.vue
- src/views/Wallet/WalletConfirmTransactionModal.vue
- tailwind.config.js
> feat: New PIN entry

- src/actions/electron/hardware-wallet.ts
Reverts radixdlt/olympia-wallet#227
> Revert "unsub transport"

- src/views/Wallet/WalletLedgerInteractionModal.vue
- src/views/Wallet/index.vue
https://www.loom.com/share/f11b7ef93bf54d51bbe7f21afaf5c903
> fix: Confirmation Modal should show warnings about the ledger not being connected for hardware wallets

- src/actions/electron/data-store.ts
- src/actions/vue/data-store.ts
- src/background.ts
- src/components/AccountListItem.vue
- src/components/ButtonSubmit.vue
- src/views/Wallet/WalletLedgerDeleteModal.vue
- src/views/Wallet/WalletSidebarAccounts.vue
- src/views/Wallet/index.vue
https://www.loom.com/share/589907422d284ae6ba40fbedb43c90f9
> Feat: forget hardware wallet

- src/views/Wallet/WalletOverview.vue
> chore: reduce overview balance font size

- src/text/index.ts
- src/views/Home/index.vue
- src/views/Wallet/WalletOverview.vue
- src/views/Wallet/index.vue
This PR removes the faucet button and the last remaining testnet copy.
> Chore: Remove all the testnet

- src/components/StakeListItem.vue
- src/views/Wallet/WalletStaking.vue
> fix: wallet stake list styling updates

- src/components/BigAmount.vue
- src/views/Wallet/WalletOverview.vue
> chore: Tooltip updates

- .github/workflows/release-main.yml
This PR updates our build process to produce builds connected to the `mainnet` network.
> feat!: prepare for mainnet

- .github/workflows/release-main.yml
Reverts radixdlt/olympia-wallet#247
> Revert "feat!: prepare for mainnet"

- src/components/StakeListItem.vue
> fix: Wallet Staking Items on max size windows

- .github/workflows/release-main.yml
- src/components/StakeListItem.vue
- src/views/CreateWallet/index.vue
- src/views/Home/index.vue
- src/views/RestoreWallet/index.vue
- src/views/Settings/SettingsResetPassword.vue
- src/views/Settings/index.vue
- src/views/Wallet/index.vue
This PR prepares the wallet for the mainnet network. Properly.
> chore: prepare for mainnet

- package.json
Release 1.0.0 as a marker for mainnet
> feat!: Mainnet Release

- src/views/Wallet/index.vue
This PR cleans up duplicate, conflicting error handling that caused a regression when created an extraneous error message after reconnecting to a disconnected ledger.
Repro steps from the linear issue:
* Launch wallet, connect/PIN in/launch app on ledger, select hardware wallet to derive
* Disconnect ledger
* Go to send screen and enter a transaction, get to confirmation screen, click confirm
* Ledger prompt modal appears, telling me I need to retry since ledger is not connected
* Connect/PIN in/launch app on ledger, click retry
* Modal disappears and tosses me back to transaction form with error, transaction is not submitted
This PR simplifies the error behavior (I think all events always includes a completion error, but that's an assumption on my part, I've not been able to find the …
> fix: Remove error handling for the completion event

- src/components/FormField.vue
- src/views/Home/HomeEnterPasscode.vue
- src/views/Settings/SettingsResetPassword.vue
- src/views/Settings/SettingsResetPin.vue
- src/views/Settings/SettingsRevealMnemonic.vue
- src/views/Settings/index.vue
- fix: Validate password input when pasting string
- chore: Cleanup unused imports
Loom: https://www.loom.com/share/4deef630aa8a4d6595e5d7054917f47f
> fix: Validate password input when pasting string

- package.json
- src/App.vue
- src/background.ts
- src/components/StakeListItem.vue
- src/helpers/network.ts
- src/preload.ts
- src/views/Home/index.vue
- src/views/Settings/SettingsResetPassword.vue
- src/views/Settings/index.vue
- src/views/Wallet/index.vue
- yarn.lock
This PR adds a small feature: When electron detects the host device is going into a suspended state (sleep), we send users currently viewing their wallet home, requiring them to enter their password to re-enter the wallet when the host device comes out of the suspended state.
> feat: On suspend, stop polling and send user home

- src/components/StakeListItem.vue
- src/components/Tooltip.vue
- src/text/index.ts
This PR warns the user about the Validator URL and displays the URL upon hovering its name via tooltip.
[Demo of Tooltip](https://www.loom.com/share/12f43902f9634d5b8bd4d8df7db0ba99)
> feat: add tooltip text upon hovering over Validator Name

- src/actions/electron/data-store.ts
- src/electron-store/migrations.ts
> chore: Migrate store structure to handle multiple network options

- src/components/AppLogo.vue
- src/components/NodeListItem.vue
- src/composables/index.ts
- src/composables/useSettingsTab.ts
- src/composables/useWallet.ts
- src/views/Home/HomeEnterPasscode.vue
- src/views/Settings/index.vue
- src/views/Wallet/index.vue
This is a very _rough_ implementation that catches an error when a user logs in and redirects them to the settings page if the currently selected node cannot be connected to.
> feat: If a user logs in and cannot connect to their node, redirect them to settings

- src/composables/useWallet.ts
- src/views/CreateWallet/index.vue
- src/views/Home/index.vue
> fix: Network connection is required for creating or restoring

- src/components/NodeListItem.vue
- src/composables/useWallet.ts
- src/views/Settings/SettingsSelectNode.vue
> chore: Show default network ids even when offline

- src/composables/useTransactions.ts
- src/composables/useWallet.ts
This PR increases the polling in all applicable places from polling every 5s to polling every 15s.
> chore: increase all polling from 5s to 15s

- src/actions/vue/data-store.ts
- src/background.ts
- src/text/index.ts
- src/views/Settings/SettingsSelectNode.vue
> chore: Add refresh option when switching networks takes a long time

- src/components/NodeListItem.vue
- src/text/index.ts
- src/views/Settings/ConfirmNetworkChangeModal.vue
- src/views/Settings/SettingsSelectNode.vue
https://www.loom.com/share/da7d5059f613496eb36247ceee78ba41
> feat: Changing nodes should be confirmed

- src/composables/useWallet.ts
- src/text/index.ts
- src/views/Wallet/WalletLedgerDeleteModal.vue
Updates the hardware wallet language in the app to hardware account.
> feat: hardware wallet -> hardware account

- src/views/Settings/index.vue
This PR just disables the Change Pin setting tab when there's no connection present.
> feat: also disable change pin when no connection

- src/components/NodeListItem.vue
- src/text/index.ts
> chore: Add message when Mainnet is unavailable

- .github/workflows/release-latest.yml
Disable Release Latest as it was racing release-please
> fix: disable release-latest

- src/text/index.ts
This PR makes a teeny tiny copy change.
> Chore: update switching node modal copy

- src/components/ErrorModalTransactionBuilding.vue
- src/composables/useStaking.ts
- src/text/index.ts
- src/views/Wallet/WalletStaking.vue
> feat: Display custom error messages for building txn errors

- CHANGELOG.md
- package.json
Reverts radixdlt/olympia-wallet#353
> Revert "chore: release 1.3.0"

- src/actions/electron/data-store.ts
- src/actions/vue/data-store.ts
- src/background.ts
- src/components/AppButtonCancel.vue
- src/components/AppButtonIcon.vue
- src/components/AppButtonSubmit.vue
- src/components/HiddenTokenBalanceListItem.vue
- src/components/OtherTokenBalanceListItem.vue
- src/components/TabsTab.vue
- src/electron-store/migrations.ts
- src/text/index.ts
- src/views/Settings/SettingsTokens.vue
- src/views/Settings/index.vue
- src/views/Wallet/WalletOverview.vue
- src/views/Wallet/WalletStaking.vue
https://www.loom.com/share/1342336cbe5447dd977c648ba2accd74
> feat: Users can hide other token types from view

- .gitignore
- README.md
- src/updater.ts
https://github.com/radixdlt/olympia-wallet/pull/383/files
> fix: Reverts the removal of dev-app-update

- src/App.vue
- src/components/ErrorModalHardware.vue
- src/composables/useTransactions.ts
- src/text/index.ts
https://www.loom.com/share/a698910ebb7841c5ab7be1c8abaa0bfd
> chore: Surface simple error when user disconnects hardware device mid-transaction

- src/App.vue
- src/composables/useWallet.ts
- src/helpers/network.ts
- src/text/index.ts
- src/views/Home/HomeEnterPasscode.vue
> chore: ping network every 10 seconds to check connectivity

- src/App.vue
- src/composables/useTransactions.ts
> fix: Correctly show hardware error modal

- src/helpers/network.ts
- src/text/index.ts
- src/views/Settings/ConfirmNetworkChangeModal.vue
> chore: Show additional warning when switching to custom node

- CHANGELOG.md
- package.json
> chore: Release v1.3.2

- src/composables/useStaking.ts
- src/views/Wallet/WalletStaking.vue
Small PR that refactors the `useStaking` composable to pull from the public ledger.
> chore: Wallet Staking positions should change as the active address changes

- src/actions/electron/data-store.ts
- src/actions/vue/data-store.ts
- src/background.ts
- src/components/AccountListItem.vue
- src/components/AccountListPreview.vue
- src/components/HardwareAccountListItem.vue
- src/composables/useWallet.ts
- src/electron-store/migrations.ts
- src/router/index.ts
- src/text/index.ts
- src/views/Account/AccountEditName.vue
- src/views/Wallet/WalletDeviceEditName.vue
- src/views/Wallet/WalletHideAccountModal.vue
- src/views/Wallet/WalletSidebarAccounts.vue
- src/views/Wallet/WalletSidebarDefault.vue
- src/views/Wallet/index.vue
**WIP**
Still need to handle the logic right after the device name is changed (IE something similar to when you change an account name and the `accountRenamed(name.value)` runs ) - Also have yet to route up and build the logic to hide specific accounts. But I have the modal built out.
> feat: polish navigation wire up all icons

- src/actions/electron/data-store.ts
- src/actions/vue/data-store.ts
- src/background.ts
- src/composables/useWallet.ts
- src/views/Wallet/WalletLedgerDeleteModal.vue
- src/views/Wallet/WalletSidebarAccounts.vue
https://www.loom.com/share/3747fa921497480dacbdc4c677928e4a
> feat: Add a new ledger device and add a new ledger account

- src/composables/useTransactions.ts
Appease the linter after merging #497
> chore: fix linter after merge

- src/background.ts
- src/helpers/debounce.ts
[Demo](https://www.loom.com/share/b840b11d338d4c738161f592908c3883)
This PR counts mouse movement and key presses as interactions and resets application if no interactions were logged within one hour.
> chore: create logic to refresh app after set time and requirements

- scripts/notarize.js
sigh, I forgot to push the change from an older laptop that has the correct signing keys in #508.  Done for the day, we can approach it tomorrow @P-v-R
> chore: notarize with apple team

- src/composables/useWallet.ts
https://www.loom.com/share/fc9e9e3650f9479a903554b87c31f4b2
> fix: creating a new hardware device broke all hardware accounts

- src/views/Wallet/WalletNewDevicePopup.vue
The on-hover styling of the "got it" button was only changing the color of the button text and not the whole button, this fixes that. Also tweaked the sizing of it.
> chore: improve new device pop up bttn hover styling

- src/actions/electron/hardware-wallet.ts
- src/composables/useWallet.ts
- src/text/index.ts
- src/views/Wallet/WalletLedgerInteractionModal.vue
@artsycoder533 this is as far as I got this evening.  Let's use this branch as a base for our other fixes.
> fix: Watch for account activation errors

- src/text/index.ts
Small copy update for the ledger error title
> chore: Update Ledger Error Title

- src/composables/useWallet.ts
[Linear Issue RDX-437](https://linear.app/township/issue/RDX-437)
> fix: New Ledgers should be named Ledgers

- src/components/AccountListItem.vue
[Linear Issue #439](https://linear.app/township/issue/RDX-439)
> fix: move pencil icon

- src/electron-store/helpers.ts
- src/electron-store/migrations.ts
[Fixes RDX-435](https://linear.app/township/issue/RDX-435)
> fix: Update default Hardware device name when upgrading

- src/components/AccountListItem.vue
- src/components/ClickToCopy.vue
- src/components/layout/WalletLayout.vue
- src/components/layout/WalletSidebarAccounts.vue
- src/components/modals/WalletLedgerVerifyAddressModal.vue
- src/components/modals/WalletLedgerVerifyErrorModal.vue
- src/composables/useTokenBalances.ts
- src/composables/useWallet.ts
- src/helpers/validateRadixTypes.ts
Fixes [RDX-434](https://linear.app/township/issue/RDX-434) by bringing back the click to copy validation for ledger addresses.
> fix: Click To Copy Ledger Regression

- src/components/AppButtonCancel.vue
- src/components/layout/WalletLayout.vue
- src/components/modals/WalletLedgerInteractionModal.vue
- src/composables/useWallet.ts
- src/text/index.ts
[See Linear Ticket RDX-456](https://linear.app/township/issue/RDX-456)
> feat: add cancel button to decryption modal

- src/views/Wallet/WalletTransaction.vue
[Linear Issue RDX-454](https://linear.app/township/issue/RDX-454)
> fix: Validate Message & Encryption combo

- CHANGELOG.md
- package.json
Prepare for the 1.6.0 release for early signing.
> chore: prepare 1.6.0 release
